apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-users
  template:
    metadata:
      labels:
        app: rso1920-users
    spec:
      containers:
      - image: rso1920/users:latest
        name: rso1920-users
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://10.28.6.185:8083
          - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
            value: http://etcd:2379/health
        ports:
        - containerPort: 8083
          name: server-users
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: server-users
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server-users
          initialDelaySeconds: 60
          periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-users
spec:
  type: ClusterIP
  ports:
  - port: 8083
    protocol: TCP
    targetPort: server-users
  selector:
    app: rso1920-users
