kumuluzee:
  name: rso1920-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: catalog-endpoint
        url-pattern: /v1/users/*

rest-config:
  channel-api-add-channel-path: /v1/channels/createChannel