kumuluzee:
  name: rso1920-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
    keycloak: http://34.65.142.129:8082
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: users-endpoint
        url-pattern: /v1/users/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="b854a7b7-ead9-432d-9dbe-720165e79cc9-ls.logit.io"
                                port="11693" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
  security:
    keycloak:
      json: '{
        "realm": "customers-realm",
        "bearer-only": true,
        "auth-server-url": "http://34.65.142.129:8082/auth/",
        "ssl-required": "external",
        "resource": "customers-api"
      }'
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"

rest-config:
  channel-api-add-channel-path: /v1/channels/createChannel